### ISSUE TITLE
Storage Space Size

### ISSUE THREAD

**Issue by Pantyhose-X** [Andrey2470T/multidecor#1]
items, wish to provide more storage space
* 16*11 for Android

```
minetest.register_chatcommand("name", {
	params = "",
	description = "",
	func = function(name, param)
		minetest.show_formspec(name, "",
				"size[16,11;]"..
				"list[detached:name;main;0,0;16,8;]"..
				"list[current_player;main;0,9;16,2;]")
		return true, ""
	end,
})
```
![AFGGGGGGGGG](https://user-images.githubusercontent.com/42504385/183235108-a847a482-30e3-4ba2-9606-178847689a0c.PNG)

**Comment by Andrey2470T** [comment]
Ermm... and for which certain furniture components do you want to extend inventory size?

**Comment by Pantyhose-X** [comment]
> Ermm... and for which certain furniture components do you want to extend inventory size?

wooden cupboard with glass doors

**Comment by Andrey2470T** [comment]
Not too much? The cupboard has two shelves places, each 8x3 size. I can increase to 8x6.

**Comment by Andrey2470T** [comment]
Increased dad6f0e1e1705e171570fbc0ce564428f9861771

**Comment by Pantyhose-X** [comment]
> Not too much? The cupboard has two shelves places, each 8x3 size. I can increase to 8x6.

Edited, please merge https://github.com/Andrey2470T/multidecor/pull/2
