### ISSUE TITLE
Fields "height_max" and "height_min" deprecated in craft_ingredients

### ISSUE THREAD

**Issue by kronwiz** [Andrey2470T/multidecor#6]
Hello,

while starting Minetest, in the craft_ingredients/ores.lua file the following warnings are raised:

WARNING[Main]: Field "height_max": Deprecated: new name is "y_max".
WARNING[Main]: Field "height_min": Deprecated: new name is "y_min".

It appears that they are due to the minetest.register_ore calls.

There's also this warning, but I'm not sure it's related to the same function: 
WARNING[Main]: register_ore: ore type requires 'noise_params' but it is not specified, falling back to defaults

This is the Minetest version I'm running (on a Raspberry Pi 3B):

Minetest 5.6.1 (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."

Regards.

**Comment by Andrey2470T** [comment]
Fixed in "1.1.0" branch bbddab87b878cd7c6cf39d7652696649df740174
